export default {
    img_signup: require('../assets/Images/img_signup.png'),
    img_categories: require('../assets/Images/img_categories.png'),
    categories_accessories: require('../assets/Images/categories_accessories.png'),
    categories_bottom: require('../assets/Images/categories_bottom.png'),
    categories_top: require('../assets/Images/categories_top.png'),
    categories_shoes: require('../assets/Images/categories_shoes.png'),
    categories_sweemwear: require('../assets/Images/categories_sweemwear.png'),
    shoes1: require('../assets/Images/shoes1.png'),
    shoes2: require('../assets/Images/shoes2.png'),
    shoes3: require('../assets/Images/shoes3.png'),
    shoes4: require('../assets/Images/shoes4.png'),
    bg: require('../assets/Images/bg.png'),
    slider_details: require('../assets/Images/slider_details.png'),
}